spring:
  application:
    name: Task_management_system
  datasource:
    url: jdbc:mysql://localhost:3306/task_management
    username: root
    password: Smart@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true